name: travel_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  http: ^0.12.2
  rxdart: ^0.25.0
  location: ^3.0.2
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

