name: travel_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  rxdart: ^0.25.0
  location: ^3.0.2
  geolocator: ^5.3.1
  permission_handler: ^5.0.0+hotfix.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

